### ISSUE TITLE
Pricing to show starting at prior to numbers

### ISSUE THREAD

**Issue by 4PR0P05** [LucasBenninger/MCDetailingWeb#35]
Just like how you added a dollar sign, please add starting at or put some fine print at the bottom of the page showing that prices are starting at and subject to changes. Perhaps the fine print may be better as there are a few things that people should know prior to protect me. In-person Ill have this conversation with them however for online lookers they should see to bring their expectations to something reasonable.

**Comment by LucasBenninger** [comment]
Pricing has since been removed from the website entirely.
